# Generated by Django 4.2 on 2023-04-11 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("whisper_api", "0002_category_post_user_comment_post_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-updated", "-created"]},
        ),
        migrations.AddField(
            model_name="post",
            name="commented",
            field=models.ManyToManyField(
                blank=True, related_name="commenters", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
