# Generated by Django 4.2 on 2023-04-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whisper_api", "0013_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="Whisper/Whisper/static/images/default-avatar-profile-icon-of-social-media-user-vector.jpg",
                null=True,
                upload_to="",
            ),
        ),
    ]
