# Generated by Django 4.2 on 2023-04-14 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whisper_api", "0016_alter_comment_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["-name"]},
        ),
    ]
