# Generated by Django 4.2 on 2023-04-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whisper_api", "0021_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="/whisper/Whisper/static/images/default-avatar-profile-icon-of-social-media-user-vector copy.jpg",
                max_length=300,
                null=True,
                upload_to="whisper/static/images",
            ),
        ),
    ]
